sudo: false

language: php

php:
  - 5.6
  - 7.0

cache:
  directories:
    - vendor
    - bin

before_script:
  - composer self-update
  # Remove composer lock to know about failed dependencies
  - rm composer.lock
  - composer install
  - mkdir build/

script:
  - bin/phpcs
  - bin/phpspec run --config phpspec.travis.yml

after_script:
  - bin/coveralls -v
